/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crcprojekt;

import java.util.Random;

/**
 *
 * @author admin
 */
public class OknoGlowne extends javax.swing.JFrame {

    /**
     * Creates new form OknoGlowne
     */
    public OknoGlowne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wyborAlgorytmu = new javax.swing.ButtonGroup();
        sygnalWe = new javax.swing.JTextField();
        sygnalNad = new javax.swing.JTextField();
        generate_signal = new javax.swing.JButton();
        sygnalWyPop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sygnalWy = new javax.swing.JTextField();
        opcjaCRC = new javax.swing.JRadioButton();
        opcjaCRCr = new javax.swing.JRadioButton();
        opcjaSDLC = new javax.swing.JRadioButton();
        opcjaSDLCr = new javax.swing.JRadioButton();
        opcjaHamming = new javax.swing.JRadioButton();
        opcjaPar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sygnalWe = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sygnalWyPop = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        generate_noise = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        compute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sygnalWe.setText("101011101000101100011");

        sygnalNad.setEditable(false);
        sygnalNad.setPreferredSize(new java.awt.Dimension(6, 20));

        generate_signal.setText("Generuj losowy sygnał");
        generate_signal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_signalActionPerformed(evt);
            }
        });

        sygnalWyPop.setEditable(false);

        jLabel1.setText("Sygnał wejściowy [0/1]");

        jLabel2.setText("Sygnał nadmiarowy");

        jLabel3.setText("Sygnał wyjściowy z poprawkami");

        jLabel4.setText("Sygnał wyjściowy bez poprawek");

        sygnalWy.setEditable(false);

        wyborAlgorytmu.add(opcjaCRC);
        opcjaCRC.setText("CRC 16");

        wyborAlgorytmu.add(opcjaCRCr);
        opcjaCRCr.setText("CRC 16 REVERSE");

        wyborAlgorytmu.add(opcjaSDLC);
        opcjaSDLC.setText("SDLC");

        wyborAlgorytmu.add(opcjaSDLCr);
        opcjaSDLCr.setText("SDLC REVERSE");

        wyborAlgorytmu.add(opcjaHamming);
        opcjaHamming.setText("kodowanie Hamminga");

        wyborAlgorytmu.add(opcjaPar);
        opcjaPar.setText("kontrola parzystości");

        jLabel1.setText("Sygnał wejściowy [0/1]");

        sygnalWe.setColumns(20);
        sygnalWe.setLineWrap(true);
        sygnalWe.setRows(5);
        sygnalWe.setText("000001011100101011100101");
        jScrollPane1.setViewportView(sygnalWe);

        jButton1.setText("Generuj losowy sygnał");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Sygnał wyjściowy z poprawkami");

        sygnalWyPop.setEditable(false);
        sygnalWyPop.setColumns(20);
        sygnalWyPop.setLineWrap(true);
        sygnalWyPop.setRows(5);
        jScrollPane4.setViewportView(sygnalWyPop);

        jLabel6.setText("Współczynnik zakłóceń");

        jLabel2.setText("Sygnał nadmiarowy");

        jLabel4.setText("Sygnał wyjściowy bez poprawek");

        jLabel5.setText("Sygnał zakłócający [XOR]");

        generate_noise.setText("Generuj zakłócenie");

        jTextField1.setText("0,01");

        informacje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        informacje.setText("INFORMACJE O BŁĘDACH");

        SygnalZakl.setColumns(20);
        SygnalZakl.setLineWrap(true);
        SygnalZakl.setRows(5);
        jScrollPane2.setViewportView(SygnalZakl);

        SygnalNad.setEditable(false);
        SygnalNad.setColumns(20);
        SygnalNad.setLineWrap(true);
        SygnalNad.setRows(5);
        jScrollPane3.setViewportView(SygnalNad);

        sygnalWy.setEditable(false);
        sygnalWy.setColumns(20);
        sygnalWy.setLineWrap(true);
        sygnalWy.setRows(5);
        jScrollPane5.setViewportView(sygnalWy);

        compute.setText("Oblicz");
        compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcjaCRC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opcjaCRCr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opcjaSDLC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcjaSDLCr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcjaHamming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcjaPar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sygnalWyPop, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sygnalWy))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sygnalWe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField1))
                                            .addComponent(jLabel5)
                                            .addComponent(generate_noise)
                                            .addComponent(sygnalZakl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(generate_signal))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sygnalNad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compute)
                                .addGap(65, 65, 65)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcjaCRC)
                    .addComponent(opcjaCRCr)
                    .addComponent(opcjaSDLC)
                    .addComponent(opcjaSDLCr)
                    .addComponent(opcjaHamming)
                    .addComponent(opcjaPar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sygnalZakl)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generate_signal)
                            .addComponent(generate_noise))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sygnalWyPop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sygnalWy, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(compute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void generate_signalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_signalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generate_signalActionPerformed

    private void computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeActionPerformed
        CRC16 crc_16 = new CRC16();
        int signal=Integer.parseInt(sygnalWe.getText());
        if(wyborAlgorytmu.getSelection()==opcjaCRC)
        {
            crc_16.update((byte)signal);
            jLabel7.setText(Integer.toString(crc_16.value)); // dodane do sprawdzenie - na razie nie dziala
        }
    }//GEN-LAST:event_computeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoGlowne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compute;
    private javax.swing.JButton generate_noise;
    private javax.swing.JButton generate_signal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton opcjaCRC;
    private javax.swing.JRadioButton opcjaCRCr;
    private javax.swing.JRadioButton opcjaHamming;
    private javax.swing.JRadioButton opcjaPar;
    private javax.swing.JRadioButton opcjaSDLC;
    private javax.swing.JRadioButton opcjaSDLCr;
    private javax.swing.JTextArea sygnalWe;
    private javax.swing.JTextArea sygnalWy;
    private javax.swing.JTextArea sygnalWyPop;
    private javax.swing.ButtonGroup wyborAlgorytmu;
    // End of variables declaration//GEN-END:variables
}

class CRC16
{
    public int value;
    public CRC16()
    {
        value = 0;
    }
    public void update(byte signal)
    {
        int a, b;
        a =(int)signal;
        for(int i=7; i>=0; i--)
        {
            a = a << 1;
            b = (a >>> 8) & 1;
            if((value & 0x8000)!=0)
            {
                value = ((value << 1) + b)^0x1021;
            }
            else
            {
                value = (value << 1) + b;
            }
        }
        value = value &0xffff;
        return;
    }
    public void reset()
    {
        value = 0;
    }
}
